
#Client settings
[client]
	#A list of entities that won't show flat ever [Syntax: "modid:entity" ]
	#[Example: "minecraft:cow"]
	entityBlacklist = [""]
	#A list of entities that will show flat even when a dimension is blacklisted [Syntax: "modid:entity,modid:dimension" ]
	#[Example: "minecraft:bee,minecraft:the_nether"]
	entityDimensionWhitelist = [""]
	#A list of dimensions that won't have flat entities [Syntax: "modid:dimension" ]
	#[Example: "minecraft:the_nether"]
	dimensionBlacklist = [""]
	#Invert the Dimension Blacklist
	invertDimensionBlacklist = false

