[client.options]
hotbar = true
show_for_common = false
square_corners = true
full_border = false
over_items = false
extra_glow = false
auto_borders = true
legendary_tooltips_sync = false

[client.options.manual_borders]
"#169c9d" = [
  "obtrophies:trophy+&entity=ars_nouveau:drygmy",
  "obtrophies:trophy+&entity=earthmobsmod:fancy_chicken",
  "obtrophies:trophy+&entity=earthmobsmod:stray_bone_spider",
  "obtrophies:trophy+&entity=earthmobsmod:tropical_slime",
  "obtrophies:trophy+&entity=minecraft:glow_squid",
  "obtrophies:trophy+&entity=minecraft:warden",
  "obtrophies:trophy+&entity=monsterplus:glow_skeleton",
  "obtrophies:trophy+&entity=veincreeper:cyan"
]
"#1d1c21" = [
  "obtrophies:trophy+&entity=earthmobsmod:umbra_cow",
  "obtrophies:trophy+&entity=earthmobsmod:wither_skeleton_wolf",
  "obtrophies:trophy+&entity=forcecraft:ender_tot",
  "obtrophies:trophy+&entity=minecraft:cave_spider",
  "obtrophies:trophy+&entity=minecraft:ender_dragon",
  "obtrophies:trophy+&entity=minecraft:enderman",
  "obtrophies:trophy+&entity=minecraft:spider",
  "obtrophies:trophy+&entity=minecraft:wither",
  "obtrophies:trophy+&entity=minecraft:wither_skeleton",
  "obtrophies:trophy+&entity=veincreeper:black",
  "obtrophies:trophy+&entity=waddles:adelie_penguin"
]
"#3ab3da" = [
  "obtrophies:trophy+&entity=forcecraft:fairy",
  "obtrophies:trophy+&entity=minecraft:allay",
  "obtrophies:trophy+&entity=minecraft:dolphin",
  "obtrophies:trophy+&entity=minecraft:vex",
  "obtrophies:trophy+&entity=sushigocrafting:tuna",
  "obtrophies:trophy+&entity=veincreeper:light_blue"
]
"#3c44a9" = [
  "obtrophies:trophy+&entity=earthmobsmod:bouldering_drowned",
  "obtrophies:trophy+&entity=earthmobsmod:lobber_drowned",
  "obtrophies:trophy+&entity=earthmobsmod:viler_witch",
  "obtrophies:trophy+&entity=forcecraft:blue_chu_chu",
  "obtrophies:trophy+&entity=minecraft:drowned",
  "obtrophies:trophy+&entity=minecraft:phantom",
  "obtrophies:trophy+&entity=minecraft:squid",
  "obtrophies:trophy+&entity=minecraft:trader_llama",
  "obtrophies:trophy+&entity=minecraft:wandering_trader",
  "obtrophies:trophy+&entity=veincreeper:blue"
]
"#474f52" = [
  "obtrophies:trophy+&entity=earthmobsmod:bouldering_zombie",
  "obtrophies:trophy+&entity=minecraft:cat",
  "obtrophies:trophy+&entity=minecraft:evoker",
  "obtrophies:trophy+&entity=minecraft:illusioner",
  "obtrophies:trophy+&entity=minecraft:pillager",
  "obtrophies:trophy+&entity=minecraft:ravager",
  "obtrophies:trophy+&entity=minecraft:silverfish",
  "obtrophies:trophy+&entity=minecraft:vindicator",
  "obtrophies:trophy+&entity=monsterplus:abyssologer",
  "obtrophies:trophy+&entity=veincreeper:gray"
]
"#5d7c15" = [
  "obtrophies:trophy+&entity=earthmobsmod:lobber_zombie",
  "obtrophies:trophy+&entity=forcecraft:green_chu_chu",
  "obtrophies:trophy+&entity=minecraft:frog",
  "obtrophies:trophy+&entity=minecraft:sniffer",
  "obtrophies:trophy+&entity=minecraft:zombie",
  "obtrophies:trophy+&entity=minecraft:zombie_horse",
  "obtrophies:trophy+&entity=minecraft:zombie_villager",
  "obtrophies:trophy+&entity=monsterplus:overgrown_skeleton",
  "obtrophies:trophy+&entity=monsterplus:swamp_zombie",
  "obtrophies:trophy+&entity=veincreeper:green"
]
"#80c71f" = [
  "obtrophies:trophy+&entity=ars_nouveau:whirlisprig",
  "obtrophies:trophy+&entity=forcecraft:creeper_tot",
  "obtrophies:trophy+&entity=minecraft:creeper",
  "obtrophies:trophy+&entity=minecraft:slime",
  "obtrophies:trophy+&entity=minecraft:turtle",
  "obtrophies:trophy+&entity=veincreeper:lime"
]
"#825432" = [
  "obtrophies:trophy+&entity=ghastcow:ghast_cow",
  "obtrophies:trophy+&entity=minecraft:bat",
  "obtrophies:trophy+&entity=minecraft:cod",
  "obtrophies:trophy+&entity=minecraft:cow",
  "obtrophies:trophy+&entity=minecraft:donkey",
  "obtrophies:trophy+&entity=minecraft:horse",
  "obtrophies:trophy+&entity=minecraft:husk",
  "obtrophies:trophy+&entity=minecraft:rabbit",
  "obtrophies:trophy+&entity=minecraft:tadpole",
  "obtrophies:trophy+&entity=minecraft:villager",
  "obtrophies:trophy+&entity=moofluids:fluid_cow",
  "obtrophies:trophy+&entity=veincreeper:brown",
  "obtrophies:trophy+&entity=vinery:mule"
]
"#8932b7" = [
  "obtrophies:trophy+&entity=earthmobsmod:bone_spider",
  "obtrophies:trophy+&entity=minecraft:endermite",
  "obtrophies:trophy+&entity=minecraft:shulker",
  "obtrophies:trophy+&entity=veincreeper:purple"
]
"#9c9d97" = [
  "obtrophies:trophy+&entity=earthmobsmod:furnace_golem",
  "obtrophies:trophy+&entity=minecraft:elder_guardian",
  "obtrophies:trophy+&entity=minecraft:guardian",
  "obtrophies:trophy+&entity=minecraft:iron_golem",
  "obtrophies:trophy+&entity=minecraft:stray",
  "obtrophies:trophy+&entity=minecraft:witch",
  "obtrophies:trophy+&entity=minecraft:wolf",
  "obtrophies:trophy+&entity=veincreeper:light_gray"
]
"#b02e26" = [
  "obtrophies:trophy+&entity=earthmobsmod:cluck_shroom",
  "obtrophies:trophy+&entity=forcecraft:red_chu_chu",
  "obtrophies:trophy+&entity=minecraft:mooshroom",
  "obtrophies:trophy+&entity=minecraft:parrot",
  "obtrophies:trophy+&entity=minecraft:salmon",
  "obtrophies:trophy+&entity=minecraft:strider",
  "obtrophies:trophy+&entity=veincreeper:red",
  "obtrophies:trophy+&entity=vinery:wandering_winemaker"
]
"#c64fbd" = [
  "obtrophies:trophy+&entity=ars_nouveau:starbuncle",
  "obtrophies:trophy+&entity=monsterplus:crystal_zombie",
  "obtrophies:trophy+&entity=veincreeper:magenta"
]
"#f38caa" = [
  "obtrophies:trophy+&entity=earthmobsmod:jumbo_rabbit",
  "obtrophies:trophy+&entity=earthmobsmod:moolip",
  "obtrophies:trophy+&entity=earthmobsmod:teacup_pig",
  "obtrophies:trophy+&entity=earthmobsmod:zombified_pig",
  "obtrophies:trophy+&entity=minecraft:axolotl",
  "obtrophies:trophy+&entity=minecraft:hoglin",
  "obtrophies:trophy+&entity=minecraft:pig",
  "obtrophies:trophy+&entity=minecraft:piglin",
  "obtrophies:trophy+&entity=minecraft:piglin_brute",
  "obtrophies:trophy+&entity=minecraft:zoglin",
  "obtrophies:trophy+&entity=minecraft:zombified_piglin",
  "obtrophies:trophy+&entity=sushigocrafting:shrimp",
  "obtrophies:trophy+&entity=veincreeper:pink"
]
"#f9801d" = [
  "obtrophies:trophy+&entity=earthmobsmod:hyper_rabbit",
  "obtrophies:trophy+&entity=earthmobsmod:magma_cow",
  "obtrophies:trophy+&entity=earthmobsmod:wooly_cow",
  "obtrophies:trophy+&entity=lava_monster:lava_monster",
  "obtrophies:trophy+&entity=minecraft:blaze",
  "obtrophies:trophy+&entity=minecraft:fox",
  "obtrophies:trophy+&entity=minecraft:magma_cube",
  "obtrophies:trophy+&entity=minecraft:pufferfish",
  "obtrophies:trophy+&entity=minecraft:tropical_fish",
  "obtrophies:trophy+&entity=monsterplus:lava_squid",
  "obtrophies:trophy+&entity=monsterplus:mother_lava_squid",
  "obtrophies:trophy+&entity=veincreeper:orange"
]
"#f9ffff" = [
  "obtrophies:trophy+&entity=colourfulgoats:goat",
  "obtrophies:trophy+&entity=colourfulllamas:llama",
  "obtrophies:trophy+&entity=earthmobsmod:albino_cow",
  "obtrophies:trophy+&entity=earthmobsmod:baby_ghast",
  "obtrophies:trophy+&entity=earthmobsmod:horned_sheep",
  "obtrophies:trophy+&entity=earthmobsmod:melon_golem",
  "obtrophies:trophy+&entity=earthmobsmod:skeleton_wolf",
  "obtrophies:trophy+&entity=energeticsheep:energetic_sheep",
  "obtrophies:trophy+&entity=minecraft:chicken",
  "obtrophies:trophy+&entity=minecraft:ghast",
  "obtrophies:trophy+&entity=minecraft:panda",
  "obtrophies:trophy+&entity=minecraft:polar_bear",
  "obtrophies:trophy+&entity=minecraft:sheep",
  "obtrophies:trophy+&entity=minecraft:skeleton",
  "obtrophies:trophy+&entity=minecraft:skeleton_horse",
  "obtrophies:trophy+&entity=minecraft:snow_golem",
  "obtrophies:trophy+&entity=monsterplus:opalescent_eye",
  "obtrophies:trophy+&entity=veincreeper:white"
]
"#ffd83d" = [
  "obtrophies:trophy+&entity=earthmobsmod:cream_cow",
  "obtrophies:trophy+&entity=earthmobsmod:moobloom",
  "obtrophies:trophy+&entity=forcecraft:gold_chu_chu",
  "obtrophies:trophy+&entity=minecraft:bee",
  "obtrophies:trophy+&entity=minecraft:camel",
  "obtrophies:trophy+&entity=minecraft:ocelot",
  "obtrophies:trophy+&entity=veincreeper:yellow"
]
