[randomcrafting-common-config]
# The whitelist of recipe types that will not be messed up by this mod. For example, "smithing" to keep smithing table recipes (upgrading diamond gear to netherite gear) away from messing up.
WHITELIST_RECIPE_TYPES = ["emeraldcraft:melter", "minecraft:smithing_trim"]
# The whitelist of recipes that will not be messed up by this mod. For example, "minecraft:stick" to make sure two planks are always crafted into four sticks.
WHITELIST_RECIPES = ["minecraft:map"]
